// The Tier-1 gallery / globe manifest, generated by `scripts/gen_manifest.py` from the render
// store (hero variant sizes, aspect) + Natural Earth. It is DATA-DERIVED and gitignored, not
// committed — so it is absent on a clean checkout (CI) and present locally and at deploy build.
//
// Pages import `manifest`/`Country` from HERE, never the raw JSON, so exactly one `@ts-ignore`
// (below) lets `astro check` type-check every consumer against the `Manifest` contract without
// the file present; the real `astro build` reads the real JSON. Keep these types in lockstep
// with gen_manifest.py's payload — tsc cannot verify the JSON against them (it may be absent).

// @ts-ignore -- generated, gitignored artifact; absent at type-check time on a clean checkout.
import rawManifest from "../data/countries.json";

export interface Country {
  slug: string;
  name: string;
  continent: string;
  /**
   * Other published spellings — "United States", "U.S.A.", "US", "USA" — for a query to reach the
   * country by. MATCHED, NEVER SHOWN: a row on screen carries the name and the continent, so this
   * is where a code or a formal title becomes typeable without appearing beside a name it repeats.
   */
  searchTerms: string[];
  /** Authored hero frame [west, south, east, north] in EPSG:4326 — the globe's fly-to target. */
  bbox: [number, number, number, number];
  /** width / height of the smallest rendered variant (1.5 fallback when unrendered). */
  aspect: number;
  /** Long-edge sizes of the rendered hero WebP variants, ascending; empty if unrendered. */
  sizes: number[];
  /** Largest rendered size, or null if unrendered. */
  native: number | null;
  rendered: boolean;
  hasBorder: boolean;
  /** Long-edge sizes of the standalone border-layer PNGs. */
  borderSizes: number[];
  hasSpotlight: boolean;
  /** Long-edge sizes of the subject-spotlight overlay WebPs (dims neighbours, strokes the boundary). */
  spotlightSizes: number[];
}

export interface Manifest {
  count: number;
  rendered: number;
  countries: Country[];
}

// `smallestRungAtLeast` moved to ./rungs — the polar caps need it too, and importing it from here
// would have pulled this module's countries.json import into the globe's cap chunk.

// A single cast, checked in both states: `rawManifest` is `any` when the JSON is absent (CI), and
// `any` converts to anything; when present, its loosely inferred JSON type overlaps `Manifest`
// enough that TypeScript accepts the assertion directly. This was `as unknown as` with a comment
// claiming the double hop was needed for the present case — measured, and it is not.
export const manifest = rawManifest as Manifest;
