// The Tier-1 gallery / globe manifest, generated by `scripts/gen_manifest.py` from the render
// store (hero variant sizes, aspect) + Natural Earth. It is DATA-DERIVED and gitignored, not
// committed — so it is absent on a clean checkout (CI) and present locally and at deploy build.
//
// Pages import `manifest`/`Country` from HERE, never the raw JSON, so exactly one `@ts-ignore`
// (below) lets `astro check` type-check every consumer against the `Manifest` contract without
// the file present; the real `astro build` reads the real JSON. Keep these types in lockstep
// with gen_manifest.py's payload — tsc cannot verify the JSON against them (it may be absent).

// @ts-ignore -- generated, gitignored artifact; absent at type-check time on a clean checkout.
import rawManifest from "../data/countries.json";

export interface Country {
  slug: string;
  name: string;
  continent: string;
  /** Authored hero frame [west, south, east, north] in EPSG:4326 — the globe's fly-to target. */
  bbox: [number, number, number, number];
  /** width / height of the smallest rendered variant (1.5 fallback when unrendered). */
  aspect: number;
  /** Long-edge sizes of the rendered hero WebP variants, ascending; empty if unrendered. */
  sizes: number[];
  /** Largest rendered size, or null if unrendered. */
  native: number | null;
  rendered: boolean;
  hasBorder: boolean;
  /** Long-edge sizes of the standalone border-layer PNGs. */
  borderSizes: number[];
  hasSpotlight: boolean;
  /** Long-edge sizes of the subject-spotlight overlay WebPs (dims neighbours, strokes the boundary). */
  spotlightSizes: number[];
}

export interface Manifest {
  count: number;
  rendered: number;
  countries: Country[];
}

/** The smallest rung that can fill `minimumPx` on its long edge, or the largest available when
 *  none can.
 *
 *  Exists for the country page, whose hero is a CSS background-image rather than an <img>, so no
 *  srcset chooses for it. That page used to take `sizes[0]` — correct only for as long as the
 *  ladder's floor happened to be the right display size, and silently wrong the moment 640/960/1280
 *  were added below it (2026-07-25). A floor states the requirement instead of relying on the
 *  ladder's shape. */
export function smallestRungAtLeast(sizes: number[], minimumPx: number): number {
  const ascending = [...sizes].sort((first, second) => first - second);
  return ascending.find((size) => size >= minimumPx) ?? ascending[ascending.length - 1];
}

// `as unknown as` because rawManifest is `any` when the JSON is absent (CI) and the loosely
// inferred JSON type when present — the double cast compiles in both states.
export const manifest = rawManifest as unknown as Manifest;
